metadata = {
    "version": "1.1.dev1",
    "author": "Tobias Brox",
    "author_short": "tobixen",
    "copyright": "Copyright 2013-2024, Tobias Brox and contributors",
    "license": "GPL-3.0",
    "license_url": "http://www.gnu.org/licenses/gpl-3.0-standalone.html",
    "maintainer": "Tobias Brox",
    "author_email": "t-plann@tobixen.no",
    "status": "Development",
    "product": "plann",
    "name": "plann",
    "description": "Simple command-line CalDAV client and planning tool, for adding and browsing calendar items, todo list items, etc.",
    "url": "https://plann.no/",
}
